* for 循环语句

In [1]:
# 循环字符串内字符
str_for_loop = 'Matplotlib'

for str_idx in str_for_loop: 
    print(str_idx)

# 循环list中元素 
list_for_loop = ['Matplotlib', 'NumPy', 'Seaborn', 'Pandas', 'Plotly', 'SK-learn']
for item_idx in list_for_loop:
    print(item_idx)

# 循环中嵌入 if 判断 
packages_visual = ['Matplotlib', 'Seaborn', 'Plotly'] 
for item_idx in list_for_loop:
    print('=================')
    print(item_idx)
    if item_idx in packages_visual:
        print('A visualization tool')

# 嵌套 for 循环 
for item_idx in list_for_loop: 
    print('===============')
    print(item_idx)
    for item_idx in item_idx:
        print(item_idx)

M
a
t
p
l
o
t
l
i
b
Matplotlib
NumPy
Seaborn
Pandas
Plotly
SK-learn
Matplotlib
A visualization tool
NumPy
Seaborn
A visualization tool
Pandas
Plotly
A visualization tool
SK-learn
Matplotlib
M
a
t
p
l
o
t
l
i
b
NumPy
N
u
m
P
y
Seaborn
S
e
a
b
o
r
n
Pandas
P
a
n
d
a
s
Plotly
P
l
o
t
l
y
SK-learn
S
K
-
l
e
a
r
n


In [2]:
#break
for x in range(10):
    if x >= 8:
        break 
    else:
        print(x) 
else:
    print("For loop finished") #当循环被 break语句打断后，else语句中的附加操作不会被执行

0
1
2
3
4
5
6
7


* while 循环语句

* 异常处理语句
  * try 语句块包含可能引发异常的代码，而 except 语句块用于处理异常情况。

In [3]:
try:
    x = 1 / 0
except ZeroDivisionError:
    print("除数不能为零")

除数不能为零


* if 条件语句

In [6]:
value = input("请输入一个数值：")
#第一层
if value.isdigit(): #用isdigit()的方法判断是否是一个数值(整数）
    number = int(value) #将数值转换为整数类型
    #第二层
    if 0 <= number <= 100:
        #第三层
        if number < 60:
            print("不及格")
        else:
            print("及格")
        #第三层结束
    else:
        print("数值不在0-100之间")
    #第二层结束
else:
    print("输入的不是一个数值")
#第一层结束

请输入一个数值： 89


及格


* break, continue, pass 语句
  * break 语句可以用来跳出当前循环。当循环执行到 break 语句时，程序将立即跳出循环体，继续执行循环外的语句。
  * continue 语句可以用来跳过当前循环中的某些语句。当循环执行到 continue 语句时，程序将立即跳过本次循环，继续执行下一次循环。
  * pass 语句什么也不做，它只是一个空语句占位符。在需要有语句的地方，但是暂时不想编写任何语句时，可以使用 pass

In [7]:
for i in range(1, 6):
    if i == 3:
        break
    print(i)

1
2


In [8]:
for i in range(1, 6):
    if i == 3:
        continue
    print(i)

1
2
4
5


In [9]:
for i in range(1, 6):
    pass
    print(i)

1
2
3
4
5


* for循环计算向量内积

In [14]:
# 计算向量内积
# 定义向量a和b 
a = [1, 2, 3, 4, 5] 
b = [6, 7, 8, 9, 0]

# 初始化内积为0 
dot_product = 0

# 使用for循环计算内积 
for i in range(len(a)):  #range(len(a)) 创建一个包含从 0 到 len(a)-1 的整数可迭代对象。
    dot_product += a[i] * b[i]

# 打印内积 
print("向量内积为：", dot_product)
print(type(range(len(a))))
print(range(len(a)))

向量内积为： 80
<class 'range'>
range(0, 5)


* ！！循环中常用的函数！！
  * range(start, stop, step)
    * start-序列起始值；stop-序列结束值（不包含）
    * step-步长；默认1
    * range函数生成的是可迭代对象，而非列表，可以节省内存空间

In [19]:
# 生成从0-4的整数序列
for i in range(4+1):
    print(i)

#生成从10-20的整数序列
for i in range(10,20+1):
    print(i)

#生成从1-10的奇数序列
for i in range(1,10+1,2):
    print(i)

#生成从10-1的倒序整数序列
for i in range(10,1-1,-1):
    print(i)

#将range（）生成的可迭代对象变成list
list(range(10,1-1,-1))

0
1
2
3
4
10
11
12
13
14
15
16
17
18
19
20
1
3
5
7
9
10
9
8
7
6
5
4
3
2
1


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

* ！！循环中常用的函数！！
  * enumerate()
  * 用于在迭代时跟踪索引的内置函数。enumerate() 函数可以将一个可迭代对象转换为一个由索引和元素组成的枚举对象。

In [36]:
fruits = ['apple', 'banana', 'cherry']
for index, fruit in enumerate(fruits):
    print(index, fruit)
'''
fruits 列表中的每个元素都会被遍历一遍，
每次遍历都会获得该元素的值和其在列表中的索引(默认从 0 开始)。
这些值分别被赋给 index 和 fruit 变量，并打印输出。
'''

0 apple
1 banana
2 cherry


'\nfruits 列表中的每个元素都会被遍历一遍，\n每次遍历都会获得该元素的值和其在列表中的索引(默认从 0 开始)。\n这些值分别被赋给 index 和 fruit 变量，并打印输出。\n'

In [21]:
fruits = ['apple', 'banana', 'cherry']
for index, fruit in enumerate(fruits,1):  #指定索引的起始编号为1
    print(index, fruit) 

1 apple
2 banana
3 cherry


* ！！循环中常用的函数！！
  * zip() 同步遍历多个对象
  * 将多个可迭代对象的元素组合成元组，然后返回这些元组组成的迭代器。
  * 在 for 循环中使用 zip() 函数可以方便地同时遍历多个可迭代对象。
  * 当这些可迭代对象的长度不同时，zip() 函数会以最短长度的可迭代对象为准进行迭代。
  * 如果想要以长度最长的可迭代对象为准进行迭代，可以用 itertools.zip_longest()。缺失元素默认以 None 补齐，或者以用户指定值补齐。

In [22]:
names = ['Alice', 'Bob', 'Charlie'] 
scores = [80, 90, 75] 
for name, score in zip(names, scores):
    print(name, score)

Alice 80
Bob 90
Charlie 75


In [ ]:
# 计算向量内积

# 定义向量a和b 
a = [1, 2, 3, 4, 5] 
b = [6, 7, 8, 9, 0]

# 初始化内积为0 
dot_product = 0

# 使用for循环计算内积 
for a_i, b_i in zip(a, b):
    dot_product += (a_i * b_i)

# 打印内积 
print("向量内积为：", dot_product)

In [24]:
#两层for循环生成二维坐标
# 自定义函数 
def custom_meshgrid(x, y):
    num_x = len(x); num_y = len(y) 
    X = []; Y = [] 
# 外层for循环 
    for i in range(num_y):
        X_row = []; Y_row = [] 

    # 内层for循环 
        for j in range(num_x):
            X_row.append(x[j])
            Y_row.append(y[i]) 
            # 生成二维数组 
    X.append(X_row); Y.append(Y_row)

    return X, Y

# 示例用法 
x = [0, 1, 2, 3, 4, 5] # 横坐标列表 
y = [0, 1, 2, 3] # 纵坐标列表 
# 调用自定义函数 
X, Y = custom_meshgrid(x, y) 
print("X坐标："); print(X) 
print("Y坐标："); print(Y)


X坐标：
[[0, 1, 2, 3, 4, 5]]
Y坐标：
[[3, 3, 3, 3, 3, 3]]


In [29]:
# 矩阵乘法：三层for循环
# 定义矩阵 A 和 B
A = [[1,2,10,20],
     [3,4,30,40],
     [5,6,50,60]]
B = [[4,2],
     [3,1],
     [40,20],
     [30,10]]
#定义全0矩阵C 用来存放结果
C = [[0,0],
     [0,0],
     [0,0]]

#矩阵乘法
#遍历A的行
for i in range(len(A)): #len(A)输出A的行数
    #遍历B的列
    for j in range(len(B[0])):  #len(B[0])输出B的行数
        #这一层相当于消去k所在的维度，即压缩
        for k in range(len(B)):
            C[i][j] += A[i][k]*B[k][j]
            #完成相应元素相乘，再求和
#输出结果
for row in C:
    print(row)

[1010, 404]
[2424, 1010]
[3838, 1616]


In [30]:
# 矩阵乘法：三层for循环
# 定义矩阵 A 和 B
A = [[1,2,10,20],
     [3,4,30,40],
     [5,6,50,60]]
B = [[4,2],
     [3,1],
     [40,20],
     [30,10]]
#定义全0矩阵C 用来存放结果
C = [[0,0],
     [0,0],
     [0,0]]

#矩阵乘法
#遍历B的列
for i in range(len(B[0])): #len(B[0])输出B的行数
    #遍历B的列
    for j in range(len(A)):  #len(A)输出A的行数
        #这一层相当于消去k所在的维度，即压缩
        for k in range(len(B)):
            C[j][i] += A[j][k]*B[k][i]
            #完成相应元素相乘，再求和
#输出结果
for row in C:
    print(row)

[1010, 404]
[2424, 1010]
[3838, 1616]


* 向量化运算——避免for循环
  * 利用 NumPy 完成向量内积、矩阵乘法运算

In [31]:
import numpy as np 
# 定义向量a和b；准确来说是一维数组 
a = np.array([1, 2, 3, 4, 5]) 
b = np.array([6, 7, 8, 9, 0])

# 计算向量内积 
dot_product = np.dot(a,b) 
# 打印内积 
print("向量内积为：", dot_product)

向量内积为： 80


In [34]:
import numpy as np
#定义矩阵A和B
A = np.array([[1,2,10,20],
              [3,4,30,40]])
B = np.array([[1,3],
              [2,4],
              [10,30],
              [20,40]])
C = A @ B; print(C) #用 @ 运算符计算矩阵乘法
D = B @ A; print(D)

[[ 505 1111]
 [1111 2525]]
[[  10   14  100  140]
 [  14   20  140  200]
 [ 100  140 1000 1400]
 [ 140  200 1400 2000]]


In [35]:
#计算numpy的计算速度
from numpy.random import randint 
num = 200 
# num * num大小方阵，0~9随机数 
A = randint(0, 10, size = (num,num)) 
B = randint(0, 10, size = (num,num))

# 使用NumPy计算矩阵乘法 
import time 
start_time = time.time() # 开始时刻 
C_1 = A @ B 
stop_time = time.time() # 结束时刻 
time_used = stop_time - start_time 
print("--- %s seconds ---" %time_used)

C = np.zeros((num,num)) # num * num大小全0方阵

# 手动计算矩阵乘法 
start_time = time.time() # 开始时刻
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]
stop_time = time.time() # 结束时刻 
time_used = stop_time - start_time 
print("--- %s seconds ---" %time_used)

--- 0.009704113006591797 seconds ---
--- 3.743328809738159 seconds ---


* 列表生成式
  * 简洁语法，用于快速生成新的列表
  * [expression for item in iterable if condition]
  * 其中 expression 表示要生成的元素，item 表示迭代的变量，iterable 表示迭代的对象，if condition 表示可选的过滤条件。

In [2]:
even_numbers = [num for num in range(1,11) if num % 2 == 0] 
'''
num 是循环中的变量，依次取遍这个范围内的每个数字。
使用条件语句 if num % 2 == 0 来筛选偶数
'''
print(even_numbers) 

[2, 4, 6, 8, 10]


In [3]:
# 列表生成式的嵌套结构
matrix = [[i * j for j in range(1, 4)] for i in range(1, 4)] 
print(matrix) # Output: [[1, 2, 3], [2, 4, 6], [3, 6, 9]]

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [7]:
# 列表生成式生成全 0 矩阵
C = [[i*j*0 for j in range(1,3)]for i in range(1,4)]
print(C)

[[0, 0], [0, 0], [0, 0]]


In [14]:
# 自定义函数模仿 numpy.linspace() 生成等差数列
def linspace(start, stop, num=50, endpoint=True):
    if num < 2:
        # 报错 
        raise ValueError("Number of samples must be at least 2")  #raise 用于引发异常
        
    # 是否包括右端点 
    if endpoint:
        step = (stop - start) / (num - 1) 
        return [start + i * step for i in range(num)] 
    else:
        step = (stop - start) / num 
        return [start + i * step for i in range(num)]

  

# 示例用法
start = 0 # 数列起点 
stop = 10 # 数列终点 
num = 21 # 数列元素 
endpoint = True # 数列包含 stop 
# 调用自定义函数生成等差数列 
values = linspace(start, stop, num, endpoint)
print(values)

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]


In [ ]:
# 自定义函数模仿 numpy.linspace() 生成等差数列
def linspace(start, stop, num=50, endpoint=True):
    if num < 2 or not isinstance(num, int):
        # 报错：num 需要是不小于2的正整数
        raise ValueError("Number of samples must be at least 2 and an integer.")
    if start == stop:
        # 报错：start 和 stop 不能相等
        raise ValueError("Start and stop cannot be the same.")
    
    # 方法1: 根据 endpoint 参数调整步长的计算
    step = (stop - start) / (num - 1 if endpoint else num)
    return [start + i * step for i in range(num)]

    # 方法2: 总是计算步长为 (stop - start) / num
    step = (stop - start) / num
    # 列表生成式中使用 if 判断来决定是否包含终点
    return [start + i * step for i in range(num + 1) if (i < num or endpoint)]

In [16]:
# 矩阵转置：一层列表生成式
def transpose(matrix):
    transposed = [] 
    rows = len(matrix) 
    cols = len(matrix[0])
    for j in range(cols): #固定列，遍历每一行，按行排列
        transposed_row = [matrix[i][j] for i in range(rows)] 
        transposed.append(transposed_row)
    return transposed

# 示例用法 
A = [[1, 2, 3], [4, 5, 6]] 
# 调用自定义函数 
B = transpose(A)
print(B)

[[1, 4], [2, 5], [3, 6]]


In [17]:
# 矩阵转置：两层列表生成式
def transpose_2(matrix):
    transposed = [] 
    rows = len(matrix) 
    cols = len(matrix[0])
     #转置后的矩阵第j行第i列的元素对应原来矩阵第i行第j列的元素
    transposed = [[matrix[j][i]for j in range(rows)] for i in range(cols)]
    return transposed

# 示例用法 
A = [[1, 2, 3], [4, 5, 6]] 
# 调用自定义函数 
B = transpose_2(A)
print(B)

[[1, 4], [2, 5], [3, 6]]


In [19]:
# 计算矩阵逐项积：两层列表生成式
# 矩阵逐项积是指两个相同矩阵中相应位置上的元素进行逐一相乘，得到一个新的矩阵
def hadamard_prod(M1, M2):
    if (len(M1) != len(M2) or len(M1[0]) != len(M2[0])):
        raise ValueError("Matrices must have the same shape")
    result = [[M1[i][j] * M2[i][j] for j in range(len(M1[0]))] for i in range(len(M1))] 
    return result

A = [[1, 2], [3, 4]] 
B = [[2, 3],[4, 5]] 
# 计算矩阵逐项积 
C = hadamard_prod(A, B)
print(C)

[[2, 6], [12, 20]]


In [20]:
# 笛卡尔积：一层列表生成式
column1 = [1, 2, 3, 4] 
column2 = ['a', 'b', 'c'] 
cartesian_product = [(x, y) for x in column1 for y in column2] #结果为列表，列表的每个元素为元组
print(cartesian_product)

[(1, 'a'), (1, 'b'), (1, 'c'), (2, 'a'), (2, 'b'), (2, 'c'), (3, 'a'), (3, 'b'), (3, 'c'), (4, 'a'), (4, 'b'), (4, 'c')]


In [23]:
# 笛卡尔积：两层列表生成式
column1 = [1, 2, 3, 4] 
column2 = ['a', 'b', 'c'] 
cartesian_product = [[(x, y) for x in column1] for y in column2] #结果为二维列表
for prod_idx in cartesian_product:
    print(prod_idx)

[(1, 'a'), (2, 'a'), (3, 'a'), (4, 'a')]
[(1, 'b'), (2, 'b'), (3, 'b'), (4, 'b')]
[(1, 'c'), (2, 'c'), (3, 'c'), (4, 'c')]


In [24]:
# 利用 itertools.product() 函数计算笛卡儿积
from itertools import product 
column1 = [1, 2, 3, 4] 
column2 = ['a', 'b', 'c']
cartesian_product = list(product(column1, column2)) 
print(cartesian_product)

[(1, 'a'), (1, 'b'), (1, 'c'), (2, 'a'), (2, 'b'), (2, 'c'), (3, 'a'), (3, 'b'), (3, 'c'), (4, 'a'), (4, 'b'), (4, 'c')]


* 迭代器 itertools
  * 迭代器是一种用于遍历数据集合的对象，它能够逐个返回数据元素，而无需提前将整个数据集加载到内存中。

In [28]:
# 不放回排列
import itertools 
string = 'abc' 
perms_all = itertools.permutations(string) 
'''
itertools.permutations用于返回指定长度的所有可能排列方式。
返回一个可迭代对象perms，其中包含了string的所有排列方式。
'''
# 全排列 
for perm_idx in perms_all:
    print(''.join(perm_idx)) # ''.join(perm_idx) 将当前排列中的元素连接成一个字符串

abc
acb
bac
bca
cab
cba


In [30]:
import itertools 
string = 'abc' 
# 3个不放回取2个的排列 
perms_2 = itertools.permutations(string, 2) 
'''
itertools.permutations 函数还有一个可选参数r，用于指定返回的排列长度。如果不指定r，则默认返回与输入序列长度相同的排列。
返回一个包含所有长度为2的排列的可迭代对象perms。
'''
for perm_idx in perms_2:
    print(''.join(perm_idx))

ab
ac
ba
bc
ca
cb


In [32]:
# 不放回组合
import itertools 
string = 'abc'
# 3个取2个的组合 
combs_2 = itertools.combinations(string, 2) 
'''
combinations 函数，传入两个参数：一个可迭代对象和一个整数，表示要选择的元素个数。
返回一个包含所有长度为2的组合的可迭代对象combs_2
'''

for combo_idx in combs_2:
    print(''.join(combo_idx))

ab
ac
bc


In [34]:
# 有放回排列
import itertools 
string = 'abc' 
# 定义元素列表 
elements = list(string) 
# 指定重复次数 
repeat = 2 
# 生成有放回排列 
permutations = itertools.product(elements, repeat=repeat) 
# 遍历并打印所有排列 
for permutation_idx in permutations:
    print(''.join(permutation_idx))

aa
ab
ac
ba
bb
bc
ca
cb
cc


In [35]:
# 有放回组合
import itertools
string = 'abc' 
# 定义元素列表 
elements = list(string)
# 指定组合长度 
length = 2
# 生成有放回组合 
combos = itertools.combinations_with_replacement(elements, length)

# 遍历并打印所有组合 
for combination_idx in combos:
    print(''.join(combination_idx))

aa
ab
ac
bb
bc
cc


In [7]:
# 练习:给定一个整数列表 [3, 5, 2, 7, 1]，找到其中的最大值和最小值，并打印两者之和。
C = [3,5,2,7,1]
for i in range(len(C)-1):
    C_max = C[i]
    C_min = C[i]
    if C[i] < C[i+1]:
        C_max = C[i+1]
    elif C[i] > C[i+1]:
        C_min = C[i+1]
print(C_max)
print(C_min)
print(C_max + C_min)

7
1
8


In [1]:
# 练习： 使用 while 循环输出 1 到 10 的所有奇数。
i = 1
while i < 11:
    if i % 2 != 0:
        print(i)
    i += 1  

1
3
5
7
9


In [3]:
# 输入一个数字并将其转换为整数，如果输入的不是数字，则提示用户重新输入直到输入数字为止
num = input('请输入一个数：')
if num.isdigit():
    num = int(num)
else:
    num = input('请重新输入一个数字：')

请输入一个数： f
请重新输入一个数字： 3


In [ ]:
while True:
    try:
        num = int(input("请输入一个数字："))
        break
    except ValueError:
        print("输入有误，请重新输入！")

print("输入的整数是：", num)

In [4]:
# 练习：求100以内的素数
prime_list = []

for num in range(2, 101):
    for i in range(2, num):
        if num % i == 0:
            break
    else:
        prime_list.append(num)

print(prime_list)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [8]:
# 练习：请用至少两种不同办法计算 1-100 中奇数之和。
odd_sum_1 = 0
for i in range(1,101,2):
    odd_sum_1 += i 
print(odd_sum_1)

2500


In [10]:
odd_sum_2 = 0
j = 0
while j <= 100:
    if j % 2 != 0:
        odd_sum_2 += j
    j += 1
print(odd_sum_2)

2500


In [19]:
# 练习：写两个函数分别计算矩阵行、列方向元素之和。
# 计算矩阵行方向元素
matrix = []
def matrixrow_sum(matrix):
    row_sum = [i*0 for i in range(len(matrix))]
    sum = 0
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            row_sum[i] += matrix[i][j]
    return row_sum

C = [[1,2,3],
     [4,5,6]]
matrixrow_sum(C)

[6, 15]

In [23]:
# 计算矩阵列方向元素
matrix = []
def matrixcol_sum(matrix):
    col_sum = [j*0 for j in range(len(matrix[0]))]
    sum = 0
    for j in range(len(matrix[0])):
        for i in range(len(matrix)):
            col_sum[j] += matrix[i][j]
    return col_sum

C = [[1,2,3],
     [4,5,6]]
matrixcol_sum(C)

[5, 7, 9]